server:
  port: 10100

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:10080/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: ${CLOUD_CONFIG_URI:https://github.com/MiSeWang/cloud-config.git}
          username: ${CLOUD_CONFIG_NAME:826303461@qq.com}
          password: ${CLOUD_CONFIG_PASSWORD:lvshiyu298}
