server:
  port: 10100
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:MiSeWang/cloud-config.git
          uri: ${CLOUD_CONFIG_URI:https://github.com/MiSeWang/cloud-config.git}
          username: ${CLOUD_CONFIG_NAME:826303461@qq.com}
          password: ${CLOUD_CONFIG_PASSWORD:lvshiyu298}
