server:
  port: 10088
spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:10080/eureka/
  instance:
    prefer-ip-address: true