server:
  port: 10088
spring:
  application:
    name: core-zuul

eureka:
  client:
    service-url:
      defaultZone: http://${CLOUD_EUREKA_INSTANCE:localhost}:10080/eureka/
  instance:
    prefer-ip-address: true